services:
  - type: web
    name: blog-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /app/.cache/ms-playwright
    disk:
      name: playwright-cache
      mountPath: /opt/render/project/.cache
      sizeGB: 1 